package me.localeconnect.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="message")
public class Message {
	private String id;
	private String msgText;
	private int deliveryStatus;
	private String eventId;
	private String sendingUserId;
	private String receivingUserId;
	/**
	 * @return the id
	 */
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	/**
	 * @return the msgText
	 */
	@DynamoDBAttribute
	public String getMsgText() {
		return msgText;
	}
	/**
	 * @return the deliveryStatus
	 */
	@DynamoDBAttribute
	public int getDeliveryStatus() {
		return deliveryStatus;
	}
	/**
	 * @return the eventId
	 */
	@DynamoDBAttribute
	public String getEventId() {
		return eventId;
	}
	/**
	 * @return the sendingUserId
	 */
	@DynamoDBAttribute
	public String getSendingUserId() {
		return sendingUserId;
	}
	/**
	 * @return the receivingUserId
	 */
	@DynamoDBAttribute
	public String getReceivingUserId() {
		return receivingUserId;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * @param msgText the msgText to set
	 */
	public void setMsgText(String msgText) {
		this.msgText = msgText;
	}
	/**
	 * @param deliveryStatus the deliveryStatus to set
	 */
	public void setDeliveryStatus(int deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}
	/**
	 * @param eventId the eventId to set
	 */
	public void setEventId(String eventId) {
		this.eventId = eventId;
	}
	/**
	 * @param sendingUserId the sendingUserId to set
	 */
	public void setSendingUserId(String sendingUserId) {
		this.sendingUserId = sendingUserId;
	}
	/**
	 * @param receivingUserId the receivingUserId to set
	 */
	public void setReceivingUserId(String receivingUserId) {
		this.receivingUserId = receivingUserId;
	}
	
	
	
	

}
