package me.localeconnect.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="user")
public class User {
	
	private String id;
	private String userName;
	private String password;
	private String email;
	private String deviceId;
	private Date joinDate;
	private boolean emailVerified;
	private String videoProfileRef;
	private String profilePicRef;
	
	
	/**
	 * @return the joinDate
	 */
	@DynamoDBAttribute
	public Date getJoinDate() {
		return joinDate;
	}
	/**
	 * @param joinDate the joinDate to set
	 */
	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}
	/**
	 * @return the emailVerified
	 */
	@DynamoDBAttribute
	public boolean isEmailVerified() {
		return emailVerified;
	}
	/**
	 * @param emailVerified the emailVerified to set
	 */
	public void setEmailVerified(boolean emailVerified) {
		this.emailVerified = emailVerified;
	}
	/**
	 * @return the videoProfileRef
	 */
	@DynamoDBAttribute
	public String getVideoProfileRef() {
		return videoProfileRef;
	}
	/**
	 * @param videoProfileRef the videoProfileRef to set
	 */
	public void setVideoProfileRef(String videoProfileRef) {
		this.videoProfileRef = videoProfileRef;
	}
	/**
	 * @return the profilePicRef
	 */
	@DynamoDBAttribute
	public String getProfilePicRef() {
		return profilePicRef;
	}
	/**
	 * @param profilePicRef the profilePicRef to set
	 */
	public void setProfilePicRef(String profilePicRef) {
		this.profilePicRef = profilePicRef;
	}

	
	/**
	 * @return the id
	 */
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * @return the userName
	 */
	@DynamoDBIndexHashKey(globalSecondaryIndexNames={ "userName"})
	@DynamoDBAttribute
	public String getUserName() {
		return userName;
	}
	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
	/**
	 * @return the password
	 */
	@DynamoDBAttribute()
	public String getPassword() {
		return password;
	}
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * @return the email
	 */
	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}
	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * @return the deviceId
	 */
	@DynamoDBAttribute
	public String getDeviceId() {
		return deviceId;
	}
	/**
	 * @param deviceId the deviceId to set
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "User [getJoinDate()=" + getJoinDate() + ", isEmailVerified()=" + isEmailVerified()
				+ ", getVideoProfileRef()=" + getVideoProfileRef() + ", getProfilePicRef()=" + getProfilePicRef()
				+ ", getId()=" + getId() + ", getUserName()=" + getUserName() + ", getPassword()=" + getPassword()
				+ ", getEmail()=" + getEmail() + ", getDeviceId()=" + getDeviceId() + "]";
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((deviceId == null) ? 0 : deviceId.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + (emailVerified ? 1231 : 1237);
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((joinDate == null) ? 0 : joinDate.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((profilePicRef == null) ? 0 : profilePicRef.hashCode());
		result = prime * result + ((userName == null) ? 0 : userName.hashCode());
		result = prime * result + ((videoProfileRef == null) ? 0 : videoProfileRef.hashCode());
		return result;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (deviceId == null) {
			if (other.deviceId != null)
				return false;
		} else if (!deviceId.equals(other.deviceId))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (emailVerified != other.emailVerified)
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (joinDate == null) {
			if (other.joinDate != null)
				return false;
		} else if (!joinDate.equals(other.joinDate))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (profilePicRef == null) {
			if (other.profilePicRef != null)
				return false;
		} else if (!profilePicRef.equals(other.profilePicRef))
			return false;
		if (userName == null) {
			if (other.userName != null)
				return false;
		} else if (!userName.equals(other.userName))
			return false;
		if (videoProfileRef == null) {
			if (other.videoProfileRef != null)
				return false;
		} else if (!videoProfileRef.equals(other.videoProfileRef))
			return false;
		return true;
	}
	
	

}
